- name: set timezone to Moscow
  timezone:
    name: Europe/Moscow

- name: install glibc-langpack-ru
  ansible.builtin.dnf:
    name:
    - glibc-langpack-ru
    - git
    state: latest
    update_cache: yes
    install_weak_deps: false