- name: install docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: install docker
  ansible.builtin.dnf:
    name:
    - docker-ce
    state: latest
    install_weak_deps: false

- name: Install docker-compose
  get_url:
    url : https://github.com/docker/compose/releases/download/v2.17.3/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: a+x

- name: symbolic link docker-compose
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link

- name: Create group docker
  group:
    name: docker
    state: present

- name: add user docker group
  ansible.builtin.user:
    name: vagrant
    groups: docker
    append: yes